// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uarc.Core.Data;

namespace Uarc.Core.Migrations
{
    [DbContext(typeof(OpcUaDataDbContext))]
    [Migration("20180914123749_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uarc.Infrastructure.Data.Models.SqlOpcUaServer", b =>
                {
                    b.Property<int>("OpcUaServerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OpcUaUrl")
                        .IsRequired();

                    b.Property<string>("ServerLabel")
                        .IsRequired();

                    b.HasKey("OpcUaServerId");

                    b.ToTable("OpcUaServer");
                });

            modelBuilder.Entity("Uarc.Infrastructure.Data.Models.SqlOpcUaVariable", b =>
                {
                    b.Property<int>("OpcUaVariableId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NodeID")
                        .IsRequired();

                    b.Property<int>("OpcUaServerId");

                    b.Property<string>("VarLabel")
                        .IsRequired();

                    b.HasKey("OpcUaVariableId");

                    b.HasIndex("OpcUaServerId");

                    b.ToTable("OpcUaVariable");
                });

            modelBuilder.Entity("Uarc.Infrastructure.Data.Models.SqlOpcUaWert", b =>
                {
                    b.Property<int>("WertId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName");

                    b.Property<int?>("SqlOpcUaVariableOpcUaVariableId");

                    b.Property<string>("Status");

                    b.Property<string>("Wert");

                    b.Property<DateTime>("Zeitstempel");

                    b.HasKey("WertId");

                    b.HasIndex("SqlOpcUaVariableOpcUaVariableId");

                    b.ToTable("OpcUaWert");
                });

            modelBuilder.Entity("Uarc.Infrastructure.Data.Models.SqlOpcUaVariable", b =>
                {
                    b.HasOne("Uarc.Infrastructure.Data.Models.SqlOpcUaServer")
                        .WithMany("OpcUaVariablen")
                        .HasForeignKey("OpcUaServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Uarc.Infrastructure.Data.Models.SqlOpcUaWert", b =>
                {
                    b.HasOne("Uarc.Infrastructure.Data.Models.SqlOpcUaVariable")
                        .WithMany("OpcUaWerte")
                        .HasForeignKey("SqlOpcUaVariableOpcUaVariableId");
                });
#pragma warning restore 612, 618
        }
    }
}
